import 'package:age_calculator/age_calculator.dart';

class Constants {
  static const List<String> cities = [
    "Islamabad",
    "Lahore",
    "Mansehra",
    // "Ali Khan",
    // "Alipur",
    // "Arifwala",
    // "Attock",
    // "Bhera",
    // "Bhalwal",
    // "Bahawalnagar",
    // "Bahawalpur",
    // "Bhakkar",
    // "Burewala",
    // "Chillianwala",
    // "Chakwal",
    // "Chichawatni",
    // "Chiniot",
    // "Chishtian",
    // "Daska",
    // "Darya Khan",
    // "Dera Ghazi",
    // "Dhaular",
    // "Dina",
    // "Dinga",
    // "Dipalpur",
    // "Faisalabad",
    // "Fateh Jhang",
    // "Ghakhar Mandi",
    // "Gojra",
    // "Gujranwala",
    // "Gujrat",
    // "Gujar Khan",
    // "Hafizabad",
    // "Haroonabad",
    // "Hasilpur",
    // "Haveli",
    // "Lakha",
    // "Jalalpur",
    // "Jattan",
    // "Jampur",
    // "Jaranwala",
    // "Jhang",
    // "Jhelum",
    // "Kalabagh",
    // "Karor Lal",
    // "Kasur",
    // "Kamalia",
    // "Kamoke",
    // "Khanewal",
    // "Khanpur",
    // "Kharian",
    // "Khushab",
    // "Kot Adu",
    // "Jauharabad",
    // "Lahore",
    // "Lalamusa",
    // "Layyah",
    // "Liaquat Pur",
    // "Lodhran",
    // "Malakwal",
    // "Mamoori",
    // "Mailsi",
    // "Mandi Bahauddin",
    // "mian Channu",
    // "Mianwali",
    // "Multan",
    // "Murree",
    // "Muridke",
    // "Mianwali Bangla",
    // "Muzaffargarh",
    // "Narowal",
    // "Okara",
    // "Renala Khurd",
    // "Pakpattan",
    // "Pattoki",
    // "Pir Mahal",
    // "Qaimpur",
    // "Qila Didar",
    // "Rabwah",
    // "Raiwind",
    // "Rajanpur",
    // "Rahim Yar",
    // "Rawalpindi",
    // "Sadiqabad",
    // "Safdarabad",
    // "Sahiwal",
    // "Sangla Hill",
    // "Sarai Alamgir",
    // "Sargodha",
    // "Shakargarh",
    // "Sheikhupura",
    // "Sialkot",
    // "Sohawa",
    // "Soianwala",
    // "Siranwali",
    // "Talagang",
    // "Taxila",
    // "Toba Tek",
    // "Vehari",
    // "Wah Cantonment",
    // "Wazirabad",
    // "Badin",
    // "Bhirkan",
    // "Rajo Khanani",
    // "Chak",
    // "Dadu",
    // "Digri",
    // "Diplo",
    // "Dokri",
    // "Ghotki",
    // "Haala",
    // "Hyderabad",
    // "Islamkot",
    // "Jacobabad",
    // "Jamshoro",
    // "Jungshahi",
    // "Kandhkot",
    // "Kandiaro",
    // "Karachi",
    // "Kashmore",
    // "Keti Bandar",
    // "Khairpur",
    // "Kotri",
    // "Larkana",
    // "Matiari",
    // "Mehar",
    // "Mirpur Khas",
    // "Mithani",
    // "Mithi",
    // "Mehrabpur",
    // "Moro",
    // "Nagarparkar",
    // "Naudero",
    // "Naushahro Feroze",
    // "Naushara",
    // "Nawabshah",
    // "Nazimabad",
    // "Qambar",
    // "Qasimabad",
    // "Ranipur",
    // "Ratodero",
    // "Rohri",
    // "Sakrand",
    // "Sanghar",
    // "Shahbandar",
    // "Shahdadkot",
    // "Shahdadpur",
    // "Shahpur Chakar",
    // "Shikarpaur",
    // "Sukkur",
    // "Tangwani",
    // "Tando Adam",
    // "Tando Allahyar",
    // "Tando Muhammad",
    // "Thatta",
    // "Umerkot",
    // "Warah",
    // "Abbottabad",
    // "Adezai",
    // "Alpuri",
    // "Akora Khattak",
    // "Ayubia",
    // "Banda Daud",
    // "Bannu",
    // "Batkhela",
    // "Battagram",
    // "Birote",
    // "Chakdara",
    // "Charsadda",
    // "Chitral",
    // "Daggar",
    // "Dargai",
    // "Darya Khan",
    // "dera Ismail",
    // "Doaba",
    // "Dir",
    // "Drosh",
    // "Hangu",
    // "Haripur",
    // "Karak",
    // "Kohat",
    // "Kulachi",
    // "Lakki Marwat",
    // "Latamber",
    // "Madyan",
    // "Mansehra",
    // "Mardan",
    // "Mastuj",
    // "Mingora",
    // "Nowshera",
    // "Paharpur",
    // "Pabbi",
    // "Peshawar",
    // "Saidu Sharif",
    // "Shorkot",
    // "Shewa Adda",
    // "Swabi",
    // "Swat",
    // "Tangi",
    // "Tank",
    // "Thall",
    // "Timergara",
    // "Tordher",
    // "Awaran",
    // "Barkhan",
    // "Chagai",
    // "Dera Bugti",
    // "Gwadar",
    // "Harnai",
    // "Jafarabad",
    // "Jhal Magsi",
    // "Kacchi",
    // "Kalat",
    // "Kech",
    // "Kharan",
    // "Khuzdar",
    // "Killa Abdullah",
    // "Killa Saifullah",
    // "Kohlu",
    // "Lasbela",
    // "Lehri",
    // "Loralai",
    // "Mastung",
    // "Musakhel",
    // "Nasirabad",
    // "Nushki",
    // "Panjgur",
    // "Pishin valley",
    // "Quetta",
    // "Sherani",
    // "Sibi",
    // "Sohbatpur",
    // "Washuk",
    // "Zhob",
    // "Ziarat"
  ];

  static const Map<String, List<Map<String, dynamic>>> hospitals = {
    "Lahore": [
      {
        'name': 'hos a',
        'hos_address': 'this is hos_address',
        'lic': '32112-123123-23',
        'hours': "2Am-5am",
        "days": "Monday to friday"
      },
      {
        'name': 'hos b',
        'lic': '32112-123123-23',
        'hos_address': 'this is hos_address',
        'hours': "2Am-5am",
        "days": "Monday to friday"
      }
    ],
    "Islamabad": [
      {
        'name': 'hos a isb',
        'hos_address': 'this is hos_address',
        'lic': '32112-123123-23',
        'hours': "2Am-5am",
        "days": "Monday to friday"
      },
      {
        'name': 'hos b isb',
        'lic': '32112-123123-23',
        'hos_address': 'this is hos_address',
        'hours': "2Am-5am",
        "days": "Monday to friday"
      }
    ],
    "Mansehra": [
      {
        'name': 'Alshifa',
        'hos_address': 'this is hos_address',
        'lic': '32112-123123-23',
        'hours': "2Am-5am",
        "days": "Monday to friday"
      },
      {
        'name': 'maham',
        'hos_address': 'this is hos_address',
        'lic': '32112-123123-23',
        'hours': "2Am-5am",
        "days": "Monday to friday"
      }
    ],
  };

  static String age(DateTime dob) {
    DateDuration duration;
    duration = AgeCalculator.age(dob);
    return duration.toString();
  }
}

class Vaccine {
  static const List<Map<String, dynamic>> vaccines = [
    {
      "id": 1,
      "name": "TB",
      "month": 1,
    },
    {
      "id": 2,
      "name": "Rota drops",
      "month": 2,
    },
    {
      "id": 3,
      "name": "Typhoid Injection",
      "month": 9,
    },
  ];

  static List<Map<String, dynamic>> getDueVaccines(String dob) {
    List<Map<String, dynamic>> dueVaccines = [];
    List<String> trimDate = dob.split("-");
    int mth = (DateTime.now().month - int.parse(trimDate[1])).abs();
    if (Vaccine.vaccines.any((element) => element["month"] < mth)) {
      for (var element in Vaccine.vaccines) {
        if (element["month"] < mth) {
          dueVaccines.add(element);
        }
      }
    }

    return dueVaccines;
  }

  // static DateTime getdateOfVaccine(String dob, int month) {
  //   List<String> trimDate = dob.split("-");
  //   List<String> newTrimDate = trimDate[2].split(' ');
  //   DateTime newDate = DateTime(int.parse(trimDate[0]),
  //       int.parse(trimDate[1]) + month, int.parse(newTrimDate[0]));
  //   return newDate;
  // }
}
